# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_train_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathnode',
            old_name='time_delta',
            new_name='time_delta_minutes',
        ),
    ]
